### ISSUE TITLE
App crashes on Android P beta (Pixel 2 XL)

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Ghost-Android#26] opened 2018-06-02 11:57 UTC
FILL THESE DETAILS FIRST:

- Ghost version: ghost.io
- App version: 1.1.3

----

I'm able to enter my blog url and logon details, Directly after that the app crashes:

IllegalArgumentException
me.vickychijwani.spectre.util.PostUtils
getStatusColor:186

**Comment by vickychijwani** [comment] 2018-06-03 22:34
Hi @jessehouwing :wave: 

I tried to reproduce this on an Android P emulator (the exact build number according to my settings is PPP2.180412.012) but was unable to. I could login, view and edit my posts as expected.

Interestingly, the crash site seems to indicate that one of your posts has an invalid status (i.e., something other than `draft`, `scheduled` or `published`):

https://github.com/TryGhost/Ghost-Android/blob/cdf899bad70cd43da2312f1069af601e38ac61c0/app/src/main/java/me/vickychijwani/spectre/util/PostUtils.java#L186

... which _should_ crash on any device but if it doesn't, it could be due to a corrupt local database, for example. So:

- Can you try wiping the app's data completely (NOTE: uninstalling _may not_ wipe all of its data) and log in again?
- Can you try logging into the same blog + user account on a different device and see if it crashes?
- Is this crash consistently reproducible on your Pixel 2 XL?
- What's your Android build number? (Settings > System > About > Advanced)

Without a reliable way to replicate, this is going to be hard to figure out.

**Comment by vickychijwani** [comment] 2018-06-04 09:14
Assuming you're talking about posts created with the Koenig beta editor, the `unable to refresh` error is being tracked in #25. I'm going to close this one as there's nothing more to do.

**Closed by vickychijwani** 2018-06-04 09:14 UTC

**Comment by jessehouwing** [comment] 2018-06-09 07:49
Looks like it indeed caused by Koenig. I like the 'hide hy default' or link to web option proposed by others.

As to the original issue. As long as ghost itself allows illegal json to be imported and served, instead of crashing the app and storing the incorrect json locally, I'd suggest:

* try parsing the json. Give a clear indication that the data couldn't be parsed, preferably with the right slug to help identify the issue.

* do not store the data locally to prevent the app from becoming useless. 

* do not overwrite local offline drafts in the process. 

The way the app handles incorrect json now could lead to data loss of locally stored data in order to get the app back up. I've also raised the issue of ghost accepting and serving bad json there.
